### ISSUE TITLE
Changing hardware output ports with invalid names crashes server

### ISSUE THREAD

**Issue by pvanallen** [netlabtoolkit/ntk#78]
1) In AnalogOut and Servo, if you input an invalid port name, the server will crash with the below error.
2) In addition, using a lower case letter is invalid
3) For other than the default ports of 3 (AnalogOut) and 9 (Servo), when a valid new port is entered, it works, but the server outputs a message such as: 1441736751169 Component pin: 10 is already in use

1441736751169 Component pin: 10 is already in use  
/Applications/NTKserver-0-6-2/modules/nlHardware/ArduinoModel.js:166
					this.outputs[pin].pin = outputPin;
					                      ^
TypeError: Cannot set property 'pin' of undefined
    at setPinMode (/Applications/NTKserver-0-6-2/modules/nlHardware/ArduinoModel.js:166:28)
    at Socket.<anonymous> (/Applications/NTKserver-0-6-2/modules/nlMultiClientSync/nlMultiClientSync.js:116:17)
    at Socket.emit (events.js:107:17)
    at Socket.onevent (/Applications/NTKserver-0-6-2/node_modules/socket.io/lib/socket.js:326:8)
    at Socket.onpacket (/Applications/NTKserver-0-6-2/node_modules/socket.io/lib/socket.js:286:12)
    at Client.ondecoded (/Applications/NTKserver-0-6-2/node_modules/socket.io/lib/client.js:181:14)
    at Decoder.Emitter.emit (/Applications/NTKserver-0-6-2/node_modules/socket.io/node_modules/socket.io-parser/node_modules/emitter/index.js:132:20)
    at Decoder.add (/Applications/NTKserver-0-6-2/node_modules/socket.io/node_modules/socket.io-parser/index.js:233:12)
    at Client.ondata (/Applications/NTKserver-0-6-2/node_modules/socket.io/lib/client.js:166:16)
    at Socket.emit (events.js:107:17)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! netlab-server@0.5.0 start: `node netlabServer.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the netlab-server@0.5.0 start script 'node netlabServer.js'.
npm ERR! This is most likely a problem with the netlab-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node netlabServer.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls netlab-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Applications/NTKserver-0-6-2/npm-debug.log

**Comment by pvanallen** [comment]
In addition, if two AnalogOuts are active, and you try to set the second one to the same port as the first, the browser will crash
